script: bash ./deploy.sh
language: node_js
node_js:
- '5'
env:
  global:
  - GH_REF: github.com/gitboxed/media.git
  - secure: p1DVbgHzpvfb2n8+GCa4L+KpVC5NnWN11TglZkwlqVlL/5Dx33pzU0yZ1F15Vv3lH1XOYa5I2rvn/evt9IXjZhLctY5USFlLd1r61mN2LAoJlZoC9NoTHh2vyIGuJhxNZWM9cHghLc1gYnY/8Xvm/j5vgPzieelhWsH6MMEvmdoTnfK3KL+nz7hbURHzyIVbj3Np4JJHbYk/J9FVIAp6dHm7Aif9wee4qc2mekAnXAB8WvUh6Sjt4wHOXxST1ppCOH+IcnNjxz0Ndq2lTYV5bnk4Y1FJAw2Nwk1ZA8NvKMhFIg89Vd7lU+ci3B2hfSE3WkACyJjdSDGGusEgk12GDaC5F5KOy/WjopIJOmgNvzCYpxNbHuN458n2eKCc29w4thk92LPkx575AeCim5PKaT+9DtjG0HRI0TkL051hTeOQaaE8iO2HMdwb4UZu2vCsQ0ezqcyg+8p/zcd2qb56ZhxHp1+T8uwawZYnAWxTRW4mAopF/39NJ/FC5WOoQyGGEujnScteeKrNf6qsPT4NuGk0npV22jeg+7FX6z3ReLhPaH//egVajCosPToStQ9TqJr+7eRfyyiq8dUIXtpMyuKQbPvZ+IhmBT9fTgehi5MaxzgDmTcJrlMCekA6FRNnYBXOabTfAgll8zoClY5pgtpRHB0hnBdjt99XOoy0/Bc=
